name = "wpt-config-api"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# Define your environment variables here (these will be set via wrangler secret put)
# REACT_APP_FIREBASE_API_KEY - stored as secret
# REACT_APP_FIREBASE_AUTH_DOMAIN - stored as secret  
# REACT_APP_FIREBASE_DATABASE_URL - stored as secret
# REACT_APP_FIREBASE_PROJECT_ID - stored as secret
# REACT_APP_FIREBASE_STORAGE_BUCKET - stored as secret
# REACT_APP_FIREBASE_MESSAGING_SENDER_ID - stored as secret
# REACT_APP_FIREBASE_APP_ID - stored as secret

[build]
command = ""
